### ISSUE TITLE
k_bar vs. p(0), p(1), ....

### ISSUE THREAD

**Issue by tjlane** [tjlane/speckle#1]
We should add the ability to make this plot to the code base.

@fperakis up for contributing your code?

**Comment by fperakis** [comment]
Hey TJ,
absolutely I would be glad to contribute. Is this part of "speckles"?

**Comment by tjlane** [comment]
@fperakis 

Yeah! Just if you have a few lines that make that plot, it would be great to have them. You can either contribute using git or email me.
